export const sunExplorationRootIds = [
  'tree_house',
  'sun_cafe',
  'sun_dock',
  'sun_market',
  'craft_workshop',
  'secret_tree',
  'hangout_spot',
  'sunset_deck',
];

export const createSunExplorationSpots = (assetPath) => [
  {
    id: 'tree_house',
    name: 'TREE HOUSE',
    image: assetPath('images/the_sun_route/tree_house.webp'),
    unlocked: true,
    parent: null,
    children: ['tree_flag', 'bed_room', 'library', 'rope_bridge'],
    item: null,
    description: 'THE SUNの中心にある、大きな木の上の集合場所。',
    kind: 'HOME BASE',
    x: '50%',
    y: '15%',
    tapX: '50%',
    tapY: '38%',
  },
  {
    id: 'tree_flag',
    name: 'TREE FLAG',
    image: assetPath('images/the_sun_route/tree_flag.webp'),
    unlocked: true,
    parent: 'tree_house',
    children: [],
    item: 'tree_flag',
    description: '木の家の屋根裏にしまわれていた、小さな冒険旗。',
    kind: 'ATTIC',
  },
  {
    id: 'bed_room',
    name: 'BED ROOM',
    image: assetPath('images/areas/sun_house.webp'),
    unlocked: true,
    parent: 'tree_house',
    children: [],
    item: null,
    description: '木漏れ日の中で住人が休む、小さく静かな部屋。',
    kind: 'PRIVATE ROOM',
  },
  {
    id: 'library',
    name: 'LIBRARY',
    image: assetPath('images/areas/sun_house_file.webp'),
    unlocked: true,
    parent: 'tree_house',
    children: [],
    item: null,
    description: '島の記録と旅の断片が並ぶ、木の中の書庫。',
    kind: 'ARCHIVE',
  },
  {
    id: 'rope_bridge',
    name: 'ROPE BRIDGE',
    image: assetPath('images/areas/touring_guide.webp'),
    unlocked: true,
    parent: 'tree_house',
    children: [],
    item: null,
    description: 'TREE HOUSEから外の景色へ続く、風に揺れる吊り橋。',
    kind: 'PASSAGE',
  },
  {
    id: 'sun_cafe',
    name: 'SUN CAFE',
    image: assetPath('images/the_sun_route/sun_cafe.webp'),
    unlocked: true,
    parent: null,
    children: ['sea_breeze_mug'],
    item: null,
    description: 'あたたかい飲み物と海風が一緒に入ってくるカフェ。',
    kind: 'FOOD SPOT',
    x: '29%',
    y: '36%',
    tapX: '58%',
    tapY: '58%',
  },
  {
    id: 'sea_breeze_mug',
    name: 'SEA BREEZE MUG',
    image: assetPath('images/the_sun_route/sea_breeze_mug.webp'),
    unlocked: true,
    parent: 'sun_cafe',
    children: [],
    item: 'sea_breeze_mug',
    description: 'SUN CAFEの窓辺で見つかる、海風のしるしが入ったマグ。',
    kind: 'CAFE ITEM',
  },
  {
    id: 'sun_dock',
    name: 'SUN DOCK',
    image: assetPath('images/the_sun_route/sun_dock.webp'),
    unlocked: true,
    parent: null,
    children: ['ticket_info'],
    item: null,
    description: '船やいかだが出る港。次の島へ向かう風を待つ場所。',
    kind: 'HARBOR',
    x: '78%',
    y: '68%',
    tapX: '61%',
    tapY: '54%',
  },
  {
    id: 'ticket_info',
    name: 'TICKET & INFO',
    image: assetPath('images/the_sun_route/sun_dock.webp'),
    unlocked: true,
    parent: 'sun_dock',
    children: ['boat_ticket'],
    item: null,
    description: 'SUN DOCKから出発する前に見る、チケットと案内の受付。',
    kind: 'DOCK GUIDE',
  },
  {
    id: 'boat_ticket',
    name: 'BOAT TICKET',
    image: assetPath('images/the_sun_route/sun_dock.webp'),
    unlocked: true,
    parent: 'ticket_info',
    children: ['boarding_pass'],
    item: null,
    description: 'SUN DOCKから次の場所へ向かうためのチケット。',
    kind: 'BOARDING ITEM',
  },
  {
    id: 'boarding_pass',
    name: 'BOARDING PASS',
    image: assetPath('images/the_sun_route/sun_dock.webp'),
    unlocked: true,
    parent: 'boat_ticket',
    children: ['departure_stamp'],
    item: null,
    description: '船に乗る前に確認するパス。次の探索へ進む準備を記録する。',
    kind: 'PASS CHECK',
  },
  {
    id: 'departure_stamp',
    name: 'DEPARTURE STAMP',
    image: assetPath('images/the_sun_route/sun_dock.webp'),
    unlocked: true,
    parent: 'boarding_pass',
    children: ['sail_permit'],
    item: null,
    description: '出発前に押す小さなスタンプ。旅立つ準備が整ったしるし。',
    kind: 'STAMP CHECK',
  },
  {
    id: 'sail_permit',
    name: 'SAIL PERMIT',
    image: assetPath('images/the_sun_route/sun_dock.webp'),
    unlocked: true,
    parent: 'departure_stamp',
    children: ['sun_voyager_pass'],
    item: null,
    description: 'SUN DOCKから船を出すための許可証。',
    kind: 'PERMIT CHECK',
  },
  {
    id: 'sun_voyager_pass',
    name: 'SUN VOYAGER PASS',
    image: assetPath('images/the_sun_route/sun_dock.webp'),
    unlocked: true,
    parent: 'sail_permit',
    children: [],
    item: 'sun_voyager_pass',
    description: '次の海へ進む準備が整ったことを示す、特別な航海パス。',
    kind: 'VOYAGER CARD',
  },
  {
    id: 'sun_market',
    name: 'SUN MARKET',
    image: assetPath('images/the_sun_route/sun_market.webp'),
    unlocked: true,
    parent: null,
    children: ['lucky_shell'],
    item: null,
    description: '旅で見つけた道具やカードを交換できるマーケット。',
    kind: 'ITEM SHOP',
    x: '38%',
    y: '58%',
    tapX: '58%',
    tapY: '54%',
  },
  {
    id: 'lucky_shell',
    name: 'LUCKY SHELL',
    image: assetPath('images/the_sun_route/lucky_shell.webp'),
    unlocked: true,
    parent: 'sun_market',
    children: [],
    item: 'lucky_shell',
    description: 'マーケットの棚で見つかる、幸運の貝殻。',
    kind: 'MARKET ITEM',
  },
  {
    id: 'craft_workshop',
    name: 'CRAFT WORKSHOP',
    image: assetPath('images/areas/bike_setting_file.webp'),
    unlocked: true,
    parent: null,
    children: ['craft_hammer'],
    item: null,
    description: '木工、手作り、DIYの職人たちが集まる工房。',
    kind: 'WORKSHOP',
    x: '66%',
    y: '42%',
    tapX: '56%',
    tapY: '58%',
  },
  {
    id: 'craft_hammer',
    name: 'CRAFT HAMMER',
    image: assetPath('images/areas/bike_setting_file.webp'),
    unlocked: true,
    parent: 'craft_workshop',
    children: [],
    item: 'craft_hammer',
    description: '工房の作業台に置かれた、ものづくりの始まりを知らせる道具。',
    kind: 'WORKSHOP ITEM',
  },
  {
    id: 'secret_tree',
    name: 'SECRET TREE',
    image: assetPath('images/the_sun_route/secret_tree.webp'),
    unlocked: true,
    parent: null,
    children: ['secret_crystal'],
    item: null,
    description: '巨大樹の中に隠された、まだ記録が少ない秘密の部屋。',
    kind: 'SECRET ROOM',
    x: '45%',
    y: '68%',
    tapX: '48%',
    tapY: '52%',
  },
  {
    id: 'secret_crystal',
    name: 'SECRET CRYSTAL',
    image: assetPath('images/the_sun_route/secret_crystal.png'),
    unlocked: true,
    parent: 'secret_tree',
    children: [],
    item: 'secret_crystal',
    description: 'SECRET TREEの奥でうっすら光る、秘密の結晶。',
    kind: 'SECRET ITEM',
  },
  {
    id: 'hangout_spot',
    name: 'HANGOUT SPOT',
    image: assetPath('images/characters/iphone_720x1280/stay_fresh_hangout_spot_iphone.webp'),
    unlocked: true,
    parent: null,
    children: ['chill_badge'],
    item: null,
    description: 'スケボー、音楽、笑い声が集まるみんなの遊び場。',
    kind: 'PLAYGROUND',
    x: '20%',
    y: '71%',
    tapX: '52%',
    tapY: '56%',
  },
  {
    id: 'chill_badge',
    name: 'CHILL BADGE',
    image: assetPath('images/characters/iphone_720x1280/chill_kitty_relaxer_card_iphone.webp'),
    unlocked: true,
    parent: 'hangout_spot',
    children: [],
    item: 'chill_badge',
    description: '遊び場のすみで見つかる、ゆるく過ごす仲間のしるし。',
    kind: 'HANGOUT ITEM',
  },
  {
    id: 'sunset_deck',
    name: 'SUNSET DECK',
    image: assetPath('images/areas/the_sun_profile.webp'),
    unlocked: true,
    parent: null,
    children: ['sunset_compass', 'light_house'],
    item: null,
    description: '夕日がいちばんきれいに見える、今日をしめくくるデッキ。',
    kind: 'VIEW POINT',
    x: '80%',
    y: '23%',
    tapX: '54%',
    tapY: '52%',
  },
  {
    id: 'sunset_compass',
    name: 'SUNSET COMPASS',
    image: assetPath('images/areas/the_sun_profile.webp'),
    unlocked: true,
    parent: 'sunset_deck',
    children: [],
    item: 'sunset_compass',
    description: 'デッキの上で夕日の方角を指していた、小さなコンパス。',
    kind: 'VIEW ITEM',
  },
  {
    id: 'light_house',
    name: 'LIGHT HOUSE',
    image: assetPath('images/areas/the_sun_profile.webp'),
    unlocked: true,
    parent: 'sunset_deck',
    children: [],
    item: null,
    description: 'SUNSET DECKの遠くで、海へ向けてゆっくり光を回す灯台。',
    kind: 'DISTANT LIGHT',
  },
];

export const createSunExplorationIndex = (spots) => (
  Object.fromEntries(spots.map((spot) => [spot.id, spot]))
);

export const auditSunExploration = (spots) => {
  const spotIds = new Set(spots.map((spot) => spot.id));
  const referencedChildren = new Set(spots.flatMap((spot) => spot.children));

  return {
    unconnected: spots.filter((spot) => (
      spot.parent !== null
      && !referencedChildren.has(spot.id)
    )),
    missingParents: spots.filter((spot) => (
      spot.parent !== null
      && !spotIds.has(spot.parent)
    )),
    missingChildren: spots.flatMap((spot) => (
      spot.children
        .filter((childId) => !spotIds.has(childId))
        .map((childId) => ({ parentId: spot.id, childId }))
    )),
    terminal: spots.filter((spot) => spot.children.length === 0),
  };
};
